apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - namespace.yaml
  - users-service.yaml
  - products-service.yaml
  - orders-service.yaml
  - api-gateway.yaml
  - ingress.yaml
